# Generated by Django 6.0.7 on 2026-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('current_quantity', models.FloatField(default=0)),
                ('reorder_threshold', models.FloatField(default=10)),
                ('target_stock', models.FloatField(default=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(default='uploaded_stock.csv', max_length=255)),
                ('total_items', models.IntegerField(default=0)),
                ('restock_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('results_json', models.JSONField(default=dict)),
            ],
        ),
    ]
